[Feature][Lei] added UI/Pagination to Permission List
upcsg-org/upcsg-website-v2 pull request #78
Opened 2024-10-09 14:29 UTC by leidc024

Title: [Feature][Lei] added UI/Pagination to Permission List

Description - 

https://github.com/user-attachments/assets/b3ae5a61-283b-4a44-a83a-a23daed14edc

https://github.com/user-attachments/assets/7eb8d2f9-a347-4fc1-9bbc-2b62b21bff6b

Reviewers - 

Assignees -

2024-10-10 07:54 UTC, maxellmilay commented on app/admin/permissions/header.tsx
add newline at end of file

2024-10-10 07:55 UTC, maxellmilay commented on package.json
> +
kindly research use the existing `react-icons` library for consistency, and then remove extra newlines

2024-10-10 07:56 UTC, maxellmilay requested changes
@leidc024 kindly address the suggestions, thank you!

2024-10-16 03:55 UTC, leidc024 commented on package.json
> +
![image](https://github.com/user-attachments/assets/b94f5721-1b42-4890-8ded-8d59bdd30099)
![image](https://github.com/user-attachments/assets/14884a02-7827-4305-8a91-4fcd4c9212eb)

replaced heroicons with react-icons

2024-10-16 04:15 UTC, leidc024 commented on app/admin/permissions/TableSection.tsx
change hero-icons to react-icons

![image](https://github.com/user-attachments/assets/018aaced-44c7-4887-b840-d809def8a7af)

2025-04-10 04:31 UTC, maxellmilay approved these changes

2025-04-10 04:31 UTC, merged